// <auto-generated />
using System;
using EM.Planilla.Infraestructure.Configuration.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EM.Planilla.Infraestructure.Migrations
{
    [DbContext(typeof(PlanillaDbContext))]
    [Migration("20260723203004_misnuevoscambios")]
    partial class misnuevoscambios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planilla")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("employees", "planilla");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ReasonStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.ToTable("loans", "planilla");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("payrolls", "planilla");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.PayrollDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PayrollId");

                    b.ToTable("payroll_details", "planilla");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Employee", b =>
                {
                    b.OwnsOne("EM.Planilla.Domain.ValueObjects.Money", "BaseSalary", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_salary");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("EM.Planilla.Domain.ValueObjects.IdentityDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("document_type");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Type", "Number")
                                .IsUnique();

                            b1.ToTable("employees", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("BaseSalary")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Loan", b =>
                {
                    b.HasOne("EM.Planilla.Domain.Entities.Employee", "Employee")
                        .WithMany("Loans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("EM.Planilla.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("LoanId");

                            b1.ToTable("loans", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.OwnsOne("EM.Planilla.Domain.ValueObjects.LoanTerm", "Term", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Months")
                                .HasColumnType("int")
                                .HasColumnName("term_months");

                            b1.HasKey("LoanId");

                            b1.ToTable("loans", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Term")
                        .IsRequired();
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Payroll", b =>
                {
                    b.OwnsOne("EM.Planilla.Domain.ValueObjects.Period", "Period", b1 =>
                        {
                            b1.Property<Guid>("PayrollId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Month")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("month");

                            b1.Property<string>("Year")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("year");

                            b1.HasKey("PayrollId");

                            b1.HasIndex("Year", "Month")
                                .IsUnique();

                            b1.ToTable("payrolls", "planilla");

                            b1.WithOwner()
                                .HasForeignKey("PayrollId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.PayrollDetail", b =>
                {
                    b.HasOne("EM.Planilla.Domain.Entities.Payroll", "Payroll")
                        .WithMany("Payments")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("EM.Planilla.Domain.Entities.Payroll", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
