<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Events\Domains\" />
    <Folder Include="Events\Integration\" />
    <Folder Include="Models\Messages\" />
    <Folder Include="Ports\Messages\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
